name: xInventories
version: '${version}'
main: sh.pcx.xinventories.XInventories
api-version: '1.21'
author: Reset65
description: Advanced per-world inventory management

# Paper library loader - downloads dependencies at runtime
libraries:
  - org.jetbrains.kotlinx:kotlinx-coroutines-core:1.9.0
  - org.jetbrains.kotlinx:kotlinx-serialization-json:1.8.1
  - com.github.ben-manes.caffeine:caffeine:3.2.3
  - com.zaxxer:HikariCP:6.2.1
  - redis.clients:jedis:5.2.0

softdepend:
  - Vault
  - PlaceholderAPI
  - Magic
  - PerWorldInventory
  - Multiverse-Inventories
  - My_Worlds

commands:
  xinventories:
    description: Main xInventories command
    aliases: [xinv, xi]
    permission: xinventories.command

permissions:
  xinventories.admin:
    description: Full admin access (does not include bypass)
    default: op
    children:
      xinventories.command: true
      xinventories.command.*: true
      xinventories.gui: true

  xinventories.command:
    description: Use base command
    default: true

  xinventories.command.reload:
    description: Reload configuration
    default: op

  xinventories.command.save:
    description: Force save inventories
    default: op

  xinventories.command.save.others:
    description: Save other players
    default: op

  xinventories.command.load:
    description: Force load inventories
    default: op

  xinventories.command.group:
    description: Manage groups
    default: op

  xinventories.command.world:
    description: Manage world assignments
    default: op

  xinventories.command.pattern:
    description: Manage patterns
    default: op

  xinventories.command.cache:
    description: Manage cache
    default: op

  xinventories.command.backup:
    description: Manage backups
    default: op

  xinventories.command.convert:
    description: Convert from other plugins
    default: op

  xinventories.command.debug:
    description: Debug commands
    default: op

  xinventories.command.balance:
    description: View economy balances
    default: op

  xinventories.command.balance.set:
    description: Set economy balances
    default: op

  xinventories.command.balance.transfer:
    description: Transfer balances between groups
    default: op

  xinventories.command.import:
    description: Import from other plugins
    default: op

  xinventories.command.sync:
    description: View sync status
    default: op

  xinventories.command.sync.unlock:
    description: Force unlock player data
    default: op

  # Versioning & Death Recovery permissions
  xinventories.command.history:
    description: View inventory history
    default: op

  xinventories.command.restore:
    description: Restore inventory versions
    default: op

  xinventories.command.snapshot:
    description: Create manual snapshots
    default: op

  xinventories.command.deaths:
    description: View death records
    default: op

  xinventories.command.deaths.restore:
    description: Restore death inventories
    default: op

  # Content Control permissions
  xinventories.command.template:
    description: Manage templates
    default: op

  xinventories.command.template.create:
    description: Create templates
    default: op

  xinventories.command.template.apply:
    description: Apply templates to players
    default: op

  xinventories.command.template.delete:
    description: Delete templates
    default: op

  xinventories.command.template.edit:
    description: Edit templates
    default: op

  xinventories.command.restrict:
    description: Manage item restrictions
    default: op

  xinventories.reset:
    description: Reset own inventory to template
    default: true

  # Advanced Groups permissions
  xinventories.command.lock:
    description: Lock and unlock player inventories
    default: op

  xinventories.lock.bypass:
    description: Bypass inventory locks
    default: op

  xinventories.gui:
    description: Access admin GUI
    default: op

  xinventories.bypass:
    description: Bypass all inventory separation
    default: false

  xinventories.bypass.*:
    description: Bypass specific groups
    default: false
